/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsWebhooksRouteImport } from './routes/docs/webhooks'
import { Route as ApiWatchTestWebhookRouteImport } from './routes/api/watch/test-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebhooksRoute = DocsWebhooksRouteImport.update({
  id: '/docs/webhooks',
  path: '/docs/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchTestWebhookRoute = ApiWatchTestWebhookRouteImport.update({
  id: '/api/watch/test-webhook',
  path: '/api/watch/test-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/booking': typeof BookingRoute
  '/privacy': typeof PrivacyRoute
  '/scheduler': typeof SchedulerRoute
  '/terms': typeof TermsRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/api/watch/test-webhook': typeof ApiWatchTestWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/booking': typeof BookingRoute
  '/privacy': typeof PrivacyRoute
  '/scheduler': typeof SchedulerRoute
  '/terms': typeof TermsRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/api/watch/test-webhook': typeof ApiWatchTestWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/booking': typeof BookingRoute
  '/privacy': typeof PrivacyRoute
  '/scheduler': typeof SchedulerRoute
  '/terms': typeof TermsRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/api/watch/test-webhook': typeof ApiWatchTestWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/booking'
    | '/privacy'
    | '/scheduler'
    | '/terms'
    | '/docs/webhooks'
    | '/api/watch/test-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/booking'
    | '/privacy'
    | '/scheduler'
    | '/terms'
    | '/docs/webhooks'
    | '/api/watch/test-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/booking'
    | '/privacy'
    | '/scheduler'
    | '/terms'
    | '/docs/webhooks'
    | '/api/watch/test-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  BookingRoute: typeof BookingRoute
  PrivacyRoute: typeof PrivacyRoute
  SchedulerRoute: typeof SchedulerRoute
  TermsRoute: typeof TermsRoute
  DocsWebhooksRoute: typeof DocsWebhooksRoute
  ApiWatchTestWebhookRoute: typeof ApiWatchTestWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/webhooks': {
      id: '/docs/webhooks'
      path: '/docs/webhooks'
      fullPath: '/docs/webhooks'
      preLoaderRoute: typeof DocsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/test-webhook': {
      id: '/api/watch/test-webhook'
      path: '/api/watch/test-webhook'
      fullPath: '/api/watch/test-webhook'
      preLoaderRoute: typeof ApiWatchTestWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  BookingRoute: BookingRoute,
  PrivacyRoute: PrivacyRoute,
  SchedulerRoute: SchedulerRoute,
  TermsRoute: TermsRoute,
  DocsWebhooksRoute: DocsWebhooksRoute,
  ApiWatchTestWebhookRoute: ApiWatchTestWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
